# 数据集参数
data:
  videos_dir: ./data/How2Sign/videos/
  keypoints_dir: ./data/How2Sign/keypoints/
  train_label_path: ./data/How2Sign/train.csv
  val_label_path: ./data/How2Sign/val.csv
  test_label_path: ./data/How2Sign/test.csv
  max_length: 300

# 模型参数
model:
  name: facebook/mbart-large-cc25
  vocab_size: ./pretrain_models/MBart_ver1
  vlp_cps: ./checkpoints/vlp_checkpoint.pth.tar


# 日志 need_save: yes or no
log:
  need_save: True
  save_path: ./log

